#!/sbin/sh

#echo "waiting ... 10sec"; sleep 1
#echo "waiting ...  9sec"; sleep 1
#echo "waiting ...  8sec"; sleep 1
#echo "waiting ...  7sec"; sleep 1
#echo "waiting ...  6sec"; sleep 1
echo "waiting ...  5sec"; sleep 1
echo "waiting ...  4sec"; sleep 1
echo "waiting ...  3sec"; sleep 1
echo "waiting ...  2sec"; sleep 1
echo "waiting ...  1sec"; sleep 1

echo "checking sdcard init.d ..."
if [[ ! -f /data/media/0/.ssh/etc/recovery_init.d ]]; then
echo "fix permissions sdcard init.d ..."
/sbin/busybox chmod 755 /data/media/0/.ssh/etc/recovery_init.d/*
echo "run-parts sdcard init.d ..."
/sbin/busybox run-parts /data/media/0/.ssh/etc/recovery_init.d
fi

